// Game Session Statuses
export const SESSION_STATUS = {
  LOBBY: "LOBBY",
  STARTED: "STARTED",
  FINISHED: "FINISHED",
};

// Turn Statuses
export const TURN_STATUS = {
  IDLE: "IDLE",
  AWAITING_D6_ROLL: "AWAITING_D6_ROLL",
  AWAITING_PATH_CHOICE: "AWAITING_PATH_CHOICE",
  AWAITING_SPECIAL_CARD: "AWAITING_SPECIAL_CARD",
  IN_CHALLENGE: "IN_CHALLENGE",
};

// Difficulties
export const DIFFICULTY = {
  EASY: "EASY",
  MEDIUM: "MEDIUM",
  HARD: "HARD",
};

// Field Types
export const FIELD_TYPE = {
  START: "START",
  EASY: "EASY",
  MEDIUM: "MEDIUM",
  HARD: "HARD",
  SPECIAL: "SPECIAL",
  FORK: "FORK",
};

// Special Cards
export const SPECIAL_CARD = {
  PERMISSION_DENIED: "PERMISSION_DENIED",
  RAGE_BAIT: "RAGE_BAIT",
  REFACTOR: "REFACTOR",
  SECOND_CHANCE: "SECOND_CHANCE",
  SHORTCUT_FOUND: "SHORTCUT_FOUND",
  ROLLBACK: "ROLLBACK",
  BOOST: "BOOST",
  JAIL: "JAIL",
};
